SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `tblAnime` (
  `aID` int(11) NOT NULL,
  `aTitle` varchar(128) COLLATE utf16_german2_ci NOT NULL,
  `aLink` varchar(512) COLLATE utf16_german2_ci NOT NULL,
  `aCreator` varchar(64) COLLATE utf16_german2_ci NOT NULL,
  `aCreatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `aTags` varchar(128) COLLATE utf16_german2_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf16 COLLATE=utf16_german2_ci;

CREATE TABLE `tblURL` (
  `uID` int(11) NOT NULL,
  `uShort` varchar(16) COLLATE utf16_german2_ci NOT NULL,
  `uLong` varchar(256) COLLATE utf16_german2_ci NOT NULL,
  `uCreatedFrom` varchar(128) COLLATE utf16_german2_ci NOT NULL,
  `uCreatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf16 COLLATE=utf16_german2_ci;

CREATE TABLE `tblUser` (
  `uName` varchar(64) COLLATE utf16_german2_ci NOT NULL,
  `uID` varchar(64) COLLATE utf16_german2_ci NOT NULL,
  `uChips` bigint(64) NOT NULL DEFAULT '1000',
  `uCreated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf16 COLLATE=utf16_german2_ci;

CREATE TABLE `tblVoting` (
  `vID` int(11) NOT NULL,
  `vMessage` varchar(256) COLLATE utf16_german2_ci NOT NULL,
  `vVotes` int(11) NOT NULL DEFAULT '0',
  `vAuthor` varchar(64) COLLATE utf16_german2_ci NOT NULL,
  `vCreated` timestamp NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf16 COLLATE=utf16_german2_ci;


ALTER TABLE `tblAnime`
  ADD PRIMARY KEY (`aID`),
  ADD KEY `FK_UID_UID` (`aCreator`);

ALTER TABLE `tblURL`
  ADD PRIMARY KEY (`uID`),
  ADD UNIQUE KEY `Short` (`uShort`);

ALTER TABLE `tblUser`
  ADD PRIMARY KEY (`uName`),
  ADD UNIQUE KEY `FK_UNIQUE` (`uID`);

ALTER TABLE `tblVoting`
  ADD PRIMARY KEY (`vID`),
  ADD UNIQUE KEY `vMessageID` (`vMessage`);


ALTER TABLE `tblAnime`
  MODIFY `aID` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tblURL`
  MODIFY `uID` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tblVoting`
  MODIFY `vID` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `tblAnime`
  ADD CONSTRAINT `FK_UID_UID` FOREIGN KEY (`aCreator`) REFERENCES `tblUser` (`uID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
